#Hibernate Configuration

spring:
  liquibase:
    change-log: classpath*:database/master.xml
    enabled: true
#  jpa:
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate.ejb.naming_strategy: org.hibernate.cfg.ImplicitNamingStrategy
#      hibernate.show_sql: true
#      hibernate.format_sql: true
#      hibernate.hbm2ddl.auto: validate